language: ruby
rvm:
- 2.5.1
before_install: gem install bundler -v 1.17.1
services:
- postgresql
before_script:
- psql -c 'create user "schorpong" with superuser password '\''schorpong'\'';' -U postgres
- psql -c 'create database "schorpong";' -U postgres
- psql -c 'create database "schorpong_test";' -U postgres
