default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: schorpong_development
  username: postgres
  password: Yxcvbnm13xy
  host: localhost
  port: 5432

test:
  <<: *default
  username: schorpong
  password: schorpong
  host: localhost
  port: 5432
  database: schorpong_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
